local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 2.0
  publish_frequency: 2.0
  rolling_window: true
  width: 12
  height: 12
  resolution: 0.05
  transform_tolerance: 0.5
  # Increased inflation for local costmap to prevent collisions
  inflation_radius:     0.2
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
  
  # Override obstacle_layer settings for local costmap
  # Don't track unknown space in local costmap to allow rotate recovery to work
  obstacle_layer:
    track_unknown_space: false